include(CheckCXXCompilerFlag)

if(CMAKE_CXX_COMPILER MATCHES ".*clang")
  set(CMAKE_COMPILER_IS_CLANGXX 1)
endif()

macro(check_CXX11)
  if(CMAKE_COMPILER_IS_GNUCXX OR CMAKE_COMPILER_IS_CLANGXX)
    check_cxx_compiler_flag(-std=c++11 HAS_CXX11)
    if(HAS_CXX11)
      set(CXX11_FLAG "-std=c++11")
    else()
      check_cxx_compiler_flag(-std=c++0x HAS_CXX0x)
      if(HAS_CXX0x)
        set(CXX11_FLAG "-std=c++0x")
      else()
        message(SEND_ERROR "Can't enable C++11 support")
      endif()
    endif()
  elseif(MSVC10 OR MSVC11)
    # Nothing to do
  else()
    message(WARNING "Unsupported compiler")
  endif()
endmacro()
